<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Extensions\" />
      <Folder Include="Models\Download\" />
      <Folder Include="Models\Installation\" />
      <Folder Include="Models\Instance\" />
      <Folder Include="Models\Java\" />
      <Folder Include="Networking\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Flurl.Http" Version="4.0.2" />
    </ItemGroup>

</Project>
